name = "subtitle-translator"
compatibility_date = "2025-08-15"
main = "src/worker.ts"

[build]
command = "npm run build"

# 环境变量
[vars]
NODE_ENV = "production"

# 兼容性标志
[compatibility_flags]
nodejs_compat = true

# 绑定
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"
